const types = {
    CREATE_NOTE: "CREATE_NOTE",
    EDIT_NOTE: "EDIT_NOTE",
    DELETE_NOTE: "DELETE_NOTE",
    LOAD_NOTES: "LOAD_NOTES",
    STORE_NOTES: "STORE_NOTES",

    REQUEST_NOTES: "REQUEST_NOTES",
}

export default types;